name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "17 6 * * 2"
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

concurrency:
  group: scorecard
  cancel-in-progress: false

jobs:
  analysis:
    permissions:
      security-events: write
      id-token: write
      actions: read
      contents: read
    uses: NWarila/terraform-template-template/.github/workflows/reusable-scorecard.yaml@f01ad21ab1bcda82b891f8086a117fc92bafaca4
